### ISSUE TITLE
As an Web Component Store user I want to have the possibility to generate a preview without the menu bar at the bottom, to show the component I want in full screen mode.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-boilerplate#8]
To help in understanding what is meant, please see the screenshot below.
![Schermata da 2023-03-30 17-59-40](https://user-images.githubusercontent.com/7909989/228896697-e1493f03-d444-47ba-9f52-6f7c8ccf7a3b.png)

**Comment by sseppi** [comment]
@sseppi will send the testin link to @mrabans and the customer care to test the functionality and create the documentation about how to use it.

@dulvui sill find a way to define a shorter link for the default configuration

We need also to define a final naming that doesn't create confusion for "Full Screen".

@dulvui Since there is no button to go back in the Store, shall we open the full screen in a new tab?

**Comment by mrabans** [comment]
@sseppi it won't be possible to set the parameters via URL, correct?

**Comment by sseppi** [comment]
@dulvui after testing the web component, I ask you to make the following little changes:

- [x] change the name of the functionality in "Open in new tab";
- [x] open the link in a new tab (target blank);
- [x] try to make the url as short as possible

Thanks!

**Comment by dulvui** [comment]
@sseppi on testingmachine I removed fullscreen-mode and fullscreen-preview and only left "open in new tab" that opens a new tab with "taget_blank"
https://webcomponents.opendatahub.testingmachine.eu/

Making the url shorter is quite difficult and I was not able to do it in a short time. For now you can delete the "attribs" parameter and the default config is taken, but it needs to be done manually, like here:
https://webcomponents.opendatahub.testingmachine.eu/webcomponent/carsharing/fullscreen

**Comment by sseppi** [comment]
@dulvui thank yoi for the implementation! 

Everything is fine for me, we can go on production.

**Comment by dulvui** [comment]
@sseppi released on prduction
